/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 bloodcell.gltf 
Author: _Bonehead14 (https://sketchfab.com/_Bonehead14)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-blood-cells-erythrocytes-657f7b34ab2e43878c4f366e3e940ebd
Title: Red Blood Cells (Erythrocytes)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bloodcell.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[0.587, 0.054, -0.223]} rotation={[0.13, -0.484, -0.593]} scale={0.176} />
    </group>
  )
}

useGLTF.preload('/bloodcell.gltf')
